[project]
name = "homekit-camera-gstreamer"
version = "1.0"
requires-python = ">=3.10"
dependencies = [
    "HAP-Python",
    "gstreamer-meta; sys_platform == 'darwin' or sys_platform == 'win32'",
]
license = "Apache-2.0"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.ruff]
target-version = "py310"
line-length = 130

[tool.ruff.lint]
select = ["E", "F", "W", "N", "UP", "B"]

[tool.ruff.lint.per-file-ignores]
"examples/*.py" = ["E402"]
"src/gst_camera/core.py" = ["E402"]
